# Generated by Django 2.2.2 on 2019-06-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('comp_date', models.DateTimeField(verbose_name='Completion Date')),
                ('status', models.CharField(choices=[('NC', 'Not completed'), ('C', 'Completed')], default='NC', max_length=20)),
            ],
        ),
    ]
